#!/bin/bash

# Script de résumé des fichiers Docker
echo "🐳 Configuration Docker pour Portfolio Chloé"
echo "=============================================="
echo ""
echo "📁 Fichiers créés:"
echo ""
echo "1️⃣  Dockerfile"
echo "   → Build multi-stage optimisé pour Next.js 16"
echo "   → Alpine Linux pour taille minimale (~200MB)"
echo "   → User non-root pour sécurité"
echo ""
echo "2️⃣  docker-compose.yml"
echo "   → Configuration pour dev et production"
echo "   → Health checks configurés"
echo "   → Limites de ressources définies"
echo ""
echo "3️⃣  .dockerignore"
echo "   → Exclut les fichiers inutiles (node_modules, git, etc)"
echo "   → Réduit la taille de l'image"
echo ""
echo "4️⃣  deploy.sh"
echo "   → Script bash pour automation du déploiement"
echo "   → Commandes: build, push, deploy, stop, logs, health, all"
echo ""
echo "5️⃣  vps-init.sh"
echo "   → Script d'initialisation du VPS"
echo "   → Installe Docker, Docker Compose, Nginx, Certbot"
echo ""
echo "6️⃣  DOCKER_DEPLOY.md"
echo "   → Guide complet de déploiement"
echo "   → Config Nginx avec SSL"
echo "   → CI/CD avec GitHub Actions"
echo "   → Troubleshooting"
echo ""
echo "7️⃣  next.config.ts"
echo "   → Mis à jour avec output: standalone"
echo "   → Headers de sécurité ajoutés"
echo ""
echo "🚀 Démarrage rapide:"
echo ""
echo "   # 1. Tester localement"
echo "   docker-compose up"
echo ""
echo "   # 2. Builder l'image"
echo "   chmod +x deploy.sh"
echo "   ./deploy.sh build"
echo ""
echo "   # 3. Pusher vers Docker Hub"
echo "   docker login"
echo "   ./deploy.sh push"
echo ""
echo "   # 4. Sur VPS - Initialiser"
echo "   ssh root@your-vps"
echo "   curl -fsSL https://raw.githubusercontent.com/you/portfolio/main/vps-init.sh | bash"
echo ""
echo "   # 5. Déployer"
echo "   cd /opt/portfolio"
echo "   git clone https://github.com/you/portfolio.git ."
echo "   ./deploy.sh all"
echo ""
echo "✨ Done! Ton portfolio est sur Docker!"
echo ""
